# generated by datamodel-codegen:
#   filename:  area_filter.schema.json
#   timestamp: 2024-06-26T05:45:17+00:00
#   command: datamodel-codegen --input ../schema/area_filter.schema.json --output area_filter_model.py

from __future__ import annotations

from enum import Enum
from typing import List

from pydantic import BaseModel, Field


class Type(Enum):
    white = 'white'
    black = 'black'


class Datum(BaseModel):
    type: Type = Field(..., title='The type Schema')
    classes: List[int] = Field(..., title='The classes Schema')
    polygons: List[List[float]] = Field(..., title='The polygons Schema')


class AreaFilterRootSchema(BaseModel):
    frame_id: str = Field(..., title='The frame_id Schema')
    data: List[Datum] = Field(..., title='The data Schema')
